const test = [
  {
    nome: "catalão",
    url: "http://192.168.5.14/",
    tag1: "On",
    tag2: "",
    tag3: "",
  },
  {
    nome: "Santa Tereza",
    url: "http://192.168.5.16/",
    tag1: "On",
    tag2: "",
    tag3: "Validação Contabil",
  },
  {
    nome: "Cristalina",
    url: "http://192.168.5.17/",
    tag1: "",
    tag2: "Off",
    tag3: "",
  },
  {
    nome: "Validação de Catalão",
    url: "http://192.168.5.42/",
    tag1: "On",
    tag2: "",
    tag3: "Validação Scripts",
  },
  {
    nome: "Moiporá",
    url: "http://192.168.5.43/",
    tag1: "On",
    tag2: "",
    tag3: "Validação Scripts",
  },
  {
    nome: " Goiandira",
    url: "http://192.168.5.44/",
    tag1: "On",
    tag2: "",
    tag3: "Validação Rescisões",
  },
  {
    nome: "Jataí",
    url: "http://192.168.5.45/",
    tag1: "On",
    tag2: "",
    tag3: "Validação Scripts",
  },
  {
    nome: "São Luiz dos Montes Belos",
    url: "http://192.168.5.46/",
    tag1: "On",
    tag2: "",
    tag3: "Simulação Rescisões",
  },
  {
    nome: "Palminópolis",
    url: "http://192.168.5.47/",
    tag1: "",
    tag2: "Off",
    tag3: "",
  },
];
