const color = [
  {
    on: "#1c5560",
    off: "#af162a",
  },
];

const test = [
  {
    nome: "catalão",
    url: "http://192.168.5.14/",
    tag1: "",
    tag2: "off",
    tag3: "Desativado Temporariamente",
    color: color[0].off,
  },
  {
    nome: "Santa Tereza",
    url: "http://192.168.5.16/",
    tag1: "On",
    tag2: "",
    tag3: "Validação Contabil",
    color: color[0].on,
  },
  {
    nome: "Cristalina",
    url: "http://192.168.5.17/",
    tag1: "",
    tag2: "off",
    tag3: "",
    color: color[0].off,
    // color: "red",
  },
  {
    nome: "Inhumas",
    url: "http://192.168.5.42/",
    tag1: "On",
    tag2: "",
    tag3: "Simulação Rescisões",
    color: color[0].on,
  },
  {
    nome: "Moiporá",
    url: "http://192.168.5.43/",
    tag1: "On",
    tag2: "",
    tag3: "Validação Scripts",
    color: color[0].on,
  },
  {
    nome: "Acreuna",
    url: "http://192.168.5.44/",
    tag1: "On",
    tag2: "",
    tag3: "Validação Scripts",
    color: color[0].on,
  },
  {
    nome: "Jataí",
    url: "http://192.168.5.45/",
    tag1: "On",
    tag2: "",
    tag3: "",
    color: color[0].on,
  },
  {
    nome: "São Luiz dos Montes Belos",
    url: "http://192.168.5.46/",
    tag1: "On",
    tag2: "",
    tag3: "Simulação Rescisões",
    color: color[0].on,
  },
  {
    nome: "Palminópolis",
    url: "http://192.168.5.47/",
    tag1: "on",
    tag2: "",
    tag3: "",
    color: color[0].on,
    // color: "red",
  },
];
